version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 0
    schedule:
      interval: 'weekly'
    groups:
      eslint:
        patterns:
          - 'eslint*'
          - '@eslint/*'
      electron-forge:
        patterns:
          - '@electron-forge/*'
